#!/bin/bash

gcc -I. -I.. -I../arch -I../lwip/src/include -I../mbedtls/include -I../mbedtls/tf-psa-crypto/include -I../mbedtls/tf-psa-crypto/drivers/builtin/include -L../build/lwip -L../build/mbedtls/library/  main.c ssl_server.c echo_server.c socket_echo_server.c netif.c pcap.c ../arch/sys_arch.c -o t -llwipcore -llwipallapps -lmbedtls -lpcap
